testinfo:
    - id: settings-search02
      title: 设置-搜索-Language
      info: 无
testcase:      
    - element_info: com.android.settings:id/search
      find_type: id
      operate_type: click
      test_intr: 搜索
      info: 1、设置一级菜单，点击搜索按钮
    - element_info: android:id/search_src_text
      find_type: id
      operate_type: set_value
      msg: languages
      info: 2、输入字符串"languages"
      is_time: 1
    - element_info: //android.widget.TextView[@resource-id='com.android.settings:id/title']
      find_type: xpath
      operate_type: click
      info: 3、在搜索结果待选区域，选择Languages
    - element_info: //android.support.v7.widget.RecyclerView[@resource-id='com.android.settings:id/list']/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]
      find_type: xpath
      operate_type: click
      info: 4、在languages&input界面，点击Languages菜单
    - element_info: com.android.settings:id/add_language
      find_type: id
      operate_type: click
      info: 5：点击 add a language
      is_time: 1
check:
    - element_info: //android.widget.TextView[@text='Add a language']
      find_type: xpath
      operate_type: get_value
      value: Add a language
      info: 判定Add a language标题是否存在
      check_time: 3
